### ISSUE TITLE
[BUG] heartbeat delay

### ISSUE THREAD

**Issue by 0xbase12** [nuvlabox/agent#64]
**Describe the bug**
Heartbeat frequency depend on too much lines in agent app code. 

**To Reproduce**
1. Deploy with a NB
2. Set refresh interval of NB to 5s

**Expected behavior**
Heartbeat sent at right frequency without being delayed.

**Additional context**

When refresh-interval is small like 5s.
We are expecting a refresh from agent every 5 s but apparently he is not able to do that.
https://github.com/nuvlabox/agent/blob/master/code/app.py#L174
After executing all the statements in the while we sleep for interval/2
For sure this code has to be enhanced. 
By threading, sleep that take into account delta of code executed before, decoupling, etc.
And now we have in that loop the job start https://github.com/nuvlabox/agent/blob/master/code/app.py#L188

Lionel comments:
I think we should enforce a minimum value for the refresh interval.
And also I think instead of sending the telemetry every interval/2, it should be the server waiting interval*2 + some seconds before setting the NB to offline.
Because currently the Agent doesn’t respect the instruction we set (refresh interval).
In the case of a data limited connection, we will have surprises.

Khaled comments
The refresh interval was set client side as an optimization to not have to retrieve NB to get this refresh interval per NB each time. So we rely only on next-heartbeat.

**Comment by cjdcordeiro** [comment]
kept the single foreground process, due to potential race conditions on file accesses

added dynamic pausing to telemetry cycle, based on previous run
