### ISSUE TITLE
[FEATURE] Add CPU metrics

### ISSUE THREAD

**Issue by RitaSousa09** [nuvlabox/agent#68]
As I understand it, you provide the average load over the last fifteen minutes. Would it be possible to add the average load over the last one and five minutes? And cpu_count and cpu_stats also if possible.

**Comment by cjdcordeiro** [comment]
implemented in https://github.com/nuvlabox/agent/commit/dd1cdf1aaafefa39d752e3d64bba766c52951c26. will be released in version 2.0 of the NuvlaBox Engine
