### ISSUE TITLE
The log of the agent grow up to the point it fill the disk

### ISSUE THREAD

**Issue by schaubl** [nuvlabox/agent#75]
I had the case twice where the agent log grow to couple of GB for both docker logs and agent.log in /opt/nuvlabox.
Once the disk was full, the system stopped working properly.

**Comment by cjdcordeiro** [comment]
what version of the NBE is this? "agent.log" is not longer used, and the docker log should be rotated up to 10 250kb files

**Comment by schaubl** [comment]
I was most probably on an older version.
Closing it for now. I will reopen it if it happens again.
