### ISSUE TITLE
[BUG] Ensure inferred location is collected

### ISSUE THREAD

**Issue by mebster** [nuvlabox/agent#82]
**Describe the bug**
The NB doesn't populate the `inferred-location` attribute in the telemetry.

**To Reproduce**

1. Deploy a NuvlaBox Engine
1. See that the `inferred-location` is not populated (e.g. API or map on the ui)

**Expected behavior**
Approximated location should be provided, hence `inferred`.

**Comment by cjdcordeiro** [comment]
cannot reproduce anymore. seems to have been fixed already
